#theme: jekyll-theme-hacker
url: https://mindtree-chennai.github.io/MTC-Hackathon/index.html
#baseurl: /agency-jekyll-theme/
#theme: jekyll-theme-merlot
#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
theme: jekyll-theme-midnight


# Site settings
title: Mindtree Chennai Hackathon 2K19
email: Chennai.Hackathon@mindtree.com
description: "View sample problem statements for Mindtree Chennai Hackathon 2K19. For queries, write to us at Chennai.Hackathon@mindtree.com"

